---
name: Dependabot Auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Fetch Metadata from Dependabot PRs
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

      - run: gh pr merge "$PR" --squash
        env:
          PR: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
